rg_name = "ramya-rg121-dev"
location = "West US 3"
rg_aks_name = "vm-aks-rg-new"
aks_location = "South India"
vnet_name = "env-vnet63-dev"
vnet_cidr = ["10.0.0.0/16"]
subnet1_name = "ram-subnet-dev-1"
subnet1_cidr = ["10.0.1.0/24"]
subnet2_name = "ram-subnet-dev-2"
subnet2_cidr = ["10.0.2.0/24"]
app_subnet_name = "app-subnet-dev"
app_subnet_cidr = ["10.0.3.0/24"]
vm_name = "env-vm-dev"
vault_name = "bc-vault63-dev"
sql_admin_password = "Suresh@6363473346"
aks_cluster_name = "aks63-dev"
sqlserver_name = "sqlserver-dev-env"
database_name = "database-dev"